Repository Petching/Petching, pull requests merged in 2023-08, with the labels that each got.

#125 [feat] 로그인 유무 헤더 반영
  client/package-lock.json
  client/package.json
  client/src/Components/Login/signInComponent.tsx
  client/src/Components/Main/Explain.tsx
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Layout/Header/GNB.tsx
  client/src/Page/Main.tsx
  client/src/Util/getUserIdFromToken.ts
  client/src/Util/types.ts
  client/src/store/login.ts
Labels: 🧃Feat

#127 [feat] board, comment request 전부 인증된 사용자만
  server/src/main/java/com/Petching/petching/board/controller/BoardController.java
  server/src/main/java/com/Petching/petching/board/dto/BoardDto.java
  server/src/main/java/com/Petching/petching/board/entity/Board.java
  server/src/main/java/com/Petching/petching/board/service/BoardService.java
  server/src/main/java/com/Petching/petching/comment/controller/CommentController.java
  server/src/main/java/com/Petching/petching/comment/dto/CommentDto.java
  server/src/main/java/com/Petching/petching/comment/entity/Comment.java
  server/src/main/java/com/Petching/petching/comment/mapper/CommentMapper.java
  server/src/main/java/com/Petching/petching/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/Petching/petching/login/jwt/controller/JwtController.java
  server/src/main/java/com/Petching/petching/login/jwt/service/JwtService.java
  server/src/main/java/com/Petching/petching/login/oauth/userInfo/JwtToken.java
  server/src/main/java/com/Petching/petching/login/service/UserLoginService.java
  server/src/main/java/com/Petching/petching/user/dto/UserResponseForChat.java
  server/src/main/java/com/Petching/petching/user/entity/User.java
  server/src/main/java/com/Petching/petching/user/service/UserService.java
Labels: 🧃Feat

#141 [refactor] request 형태 token으로 변경으로 인한 API 문서 수정
  server/src/docs/asciidoc/Comment-API.adoc
  server/src/docs/asciidoc/자랑하기-API.adoc
  server/src/main/java/com/Petching/petching/board/entity/Board.java
  server/src/main/java/com/Petching/petching/login/jwt/service/JwtService.java
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CommentControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/comment/CommentControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
Labels: refactor

#142 [refactor] entity 변경으로 StubData 수정
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
Labels: refactor

#143 [refactor] UserControllerTest Test logic 수정
  server/src/main/java/com/Petching/petching/user/dto/UserResponseForChat.java
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: refactor

#147 [feat] CarePostController API 문서, 기존 API 문서 수정.
  server/src/docs/asciidoc/CarePost-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/자랑하기-API.adoc
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: 🧃Feat

#149 [feat] 로그인 유무 반영 / MyPets 관련 기능 구현
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/MyPets.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchMyPet.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Hook/usePostMyPet.ts
  client/src/Layout/Header/GNB.tsx
Labels: 🧃Feat

#151 [feat] Refresh Token을 이용한 access token 재발급 API
  server/src/main/java/com/Petching/petching/global/api/jwt/controller/JwtController.java
  server/src/main/java/com/Petching/petching/login/jwt/controller/JwtController.java
  server/src/main/java/com/Petching/petching/login/oauth/userInfo/JwtToken.java
Labels: 🧃Feat

#152 [feat] Refresh Token을 이용한 access token 재발급 API
  server/src/docs/asciidoc/CarePost-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/자랑하기-API.adoc
  server/src/main/java/com/Petching/petching/global/api/jwt/controller/JwtController.java
  server/src/main/java/com/Petching/petching/login/jwt/controller/JwtController.java
  server/src/main/java/com/Petching/petching/login/oauth/userInfo/JwtToken.java
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-headers.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: 🧃Feat

#158 [fe] usegetpeacock
  client/src/Components/peacockComponent.tsx
  client/src/Hook/useGetPeacock.ts
  client/src/Hook/usePostPeacock.ts
  client/src/Page/Peacock.tsx
  client/src/Page/peacockDetail.tsx
  client/src/Page/peacockWrite.tsx
  client/src/router.tsx
Labels: 🧃Feat

#163 [feat] UserProfile 및 MyPets 관련 기능 구현
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/MyPets.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useDeleteMyPet.ts
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/usePatchMyPet.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Hook/usePostMyPet.ts
  client/src/Util/postImg.ts
Labels: 🧃Feat

#169 [refactor] User Dto 수정으로 인한 테스트 코드 수정 및 S3 upload 엔드포인트 추가
  server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
Labels: refactor

#174 [fix] GNB 프로필 이미지가 뜨지 않는 현상 수정
  client/src/Hook/useDeleteMyPet.ts
  client/src/Hook/useDeleteUserProfile.ts
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchMyPet.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Hook/usePostMyPet.ts
  client/src/Layout/Header/GNB.tsx
Labels: bug, 🧃Feat

#175 [fix] 로그인 헤더 변경 안되는 현상 수정
  client/src/Layout/Header/GNB.tsx
Labels: bug

#177 [feat] 비밀번호 변경 기능 구현
  client/src/API/user.ts
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/MyPets.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Layout/Header/GNB.tsx
  client/src/Util/types.ts
Labels: 🧃Feat, refactor

#179 [refactor] User logic, CarePost entity 및 Dto 수정으로 인한 테스트 코드, API 문서 수정
  server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
  server/src/main/java/com/Petching/petching/carepost/mapper/CarePostMapper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: refactor

#181 [refactor] .env 연결 변경
  client/src/API/signUp.ts
  client/src/API/user.ts
  client/src/Components/User/Warning.tsx
  client/src/Hook/useDeleteMyPet.ts
  client/src/Hook/useDeleteUserProfile.ts
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchMyPet.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Hook/usePostMyPet.ts
  client/src/Util/postImg.ts
Labels: refactor

#182 [refactor] 로그아웃/회원탈퇴시 쿠키(리프레시토큰)제거 로직 추가
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useDeleteUserProfile.ts
  client/src/Layout/Header/GNB.tsx
  client/src/Util/getCookie.ts
Labels: refactor

#184 [feat] 모달 컴포넌트 구현
  client/src/Components/Common/Warning.tsx
  client/src/Components/User/MyPets.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Components/User/Warning.tsx
Labels: 🧃Feat

#186 [feat] MyPet controller 테스트 코드 작성 및 API 문서화
  server/src/docs/asciidoc/MyPet-API.adoc
  server/src/docs/asciidoc/User-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/Petching/petching/carepost/controller/CarePostController.java
  server/src/main/java/com/Petching/petching/carepost/dto/CarePostDto.java
  server/src/main/java/com/Petching/petching/carepost/entity/CarePost.java
  server/src/main/java/com/Petching/petching/carepost/mapper/CarePostMapper.java
  server/src/main/java/com/Petching/petching/carepost/service/CarePostService.java
  server/src/main/java/com/Petching/petching/chat/config/KafkaConsumerConfig.java
  server/src/main/java/com/Petching/petching/chat/config/KafkaProducerConfig.java
  server/src/main/java/com/Petching/petching/chat/controller/ChatRoomController.java
  server/src/main/java/com/Petching/petching/chat/controller/MessageController.java
  server/src/main/java/com/Petching/petching/chat/dto/ChatMessageDto.java
  server/src/main/java/com/Petching/petching/chat/dto/ChatRoomDto.java
  server/src/main/java/com/Petching/petching/chat/entity/ChatMessage.java
  server/src/main/java/com/Petching/petching/chat/entity/ChatRoom.java
  server/src/main/java/com/Petching/petching/chat/repository/ChatMessageRepository.java
  server/src/main/java/com/Petching/petching/chat/repository/ChatRoomRepository.java
  server/src/main/java/com/Petching/petching/chat/service/ChatRoomService.java
  server/src/main/java/com/Petching/petching/chat/service/KafkaConsumerService.java
  server/src/main/java/com/Petching/petching/chat/service/KafkaProducerService.java
  server/src/main/java/com/Petching/petching/myPet/dto/MyPetDto.java
  server/src/main/java/com/Petching/petching/tag/petSize/CarePost_PetSize.java
  server/src/main/java/com/Petching/petching/tag/petSize/CarePost_PetSizeRepository.java
  server/src/main/java/com/Petching/petching/tag/petSize/PetSize.java
  server/src/main/java/com/Petching/petching/tag/petSize/PetSizeRepository.java
  server/src/main/java/com/Petching/petching/user/controller/UserController.java
  server/src/main/java/com/Petching/petching/user/dto/UserPatchDto.java
  server/src/main/java/com/Petching/petching/user/entity/User.java
  server/src/main/java/com/Petching/petching/user/service/UserService.java
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/MyPetControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/mock/ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/mypet/MyPetControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: 🧃Feat

#187 [feat] 이미지 삭제 함수 구현
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Util/postImg.ts
Labels: 🧃Feat

#188 [refactor] BASE_URL 관리 변경
  client/src/API/api.ts
  client/src/API/user.ts
  client/src/Hook/useDeleteMyPet.ts
  client/src/Hook/useDeleteUserProfile.ts
  client/src/Hook/useGetMainData.ts
  client/src/Hook/useGetMyPets.ts
  client/src/Hook/useGetMyPostToCare.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchMyPet.ts
  client/src/Hook/usePatchUserProfile.ts
  client/src/Hook/usePostMyPet.ts
  client/src/Util/postImg.ts
Labels: refactor

#194 [feat] MyPost 임의 구현, 버튼 CSS 수정
  client/src/Components/User/MyPost.tsx
  client/src/Page/User.tsx
Labels: 🧃Feat

#196 [fix] eslint 오류 수정
  client/src/Components/User/MyPost.tsx
Labels: bug

#200 [refactor] CarePost Dto 수정으로 인한 테스트 코드 수정 및 API 문서 반영
  server/src/docs/asciidoc/CarePost-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/MyPet-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/login/LoginTest.java
Labels: refactor

#201 [refactor] CarePost Dto 수정으로 인한 테스트 코드 수정 및 API 문서 반영
  server/src/docs/asciidoc/CarePost-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/Petching/petching/carepost/dto/CarePostDto.java
  server/src/main/java/com/Petching/petching/carepost/mapper/CarePostMapper.java
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/MyPet-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/CarePostControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/login/LoginTest.java
Labels: refactor

#211 [feat] 작성한 게시글(돌봄리스트)기능 구현
  client/src/Components/User/MyPost.tsx
  client/src/Hook/useGetMyPostToCare.ts
Labels: 🧃Feat

#213 [feat] 좋아요 게시글 조회 기능 (임시)구현
  client/src/Components/User/MyLikes.tsx
  client/src/Hook/useGetUserLikes.ts
  client/src/Page/User.tsx
Labels: 🧃Feat

#215 [design] 변경된 컬러 적용
  client/src/Components/User/MyPost.tsx
  client/src/Components/User/PageBtns.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Layout/Header/GNB.tsx
  client/src/Layout/Header/Header.tsx
  client/src/Page/User.tsx
Labels: ✨Layout

#216 [feat] 닉네임 중복확인 기능 구현
  client/src/Components/Inquery/SearchInput.tsx
  client/src/Components/User/UserInfo.tsx
Labels: 🧃Feat

#223 [feat] 작성한 게시글이 없을 경우 표시 기능 구현
  client/src/Components/User/MyPost.tsx
  client/src/Util/navigateToCareListDetail.ts
Labels: 🧃Feat

#225 [fix] 데이터명 오류 수정
  client/src/Components/Care/Card.tsx
  client/src/Components/User/MyLikes.tsx
  client/src/Components/User/MyPost.tsx
  client/src/Page/CareList.tsx
  client/src/Util/types.ts
Labels: bug

#227 [refactor] card 타입 변경 및 함수 이동
  client/src/Components/Care/Card.tsx
  client/src/Components/User/MyLikes.tsx
  client/src/Components/User/MyPost.tsx
  client/src/Page/CareList.tsx
  client/src/Util/types.ts
Labels: refactor

#229 [feat] 깃허브 링크 연결
  client/src/Layout/Footer/Footer.tsx
Labels: 🧃Feat

#230 [design] 문의하기 명칭 변경, 디자인 수정
  client/src/Layout/Footer/Footer.tsx
Labels: ✨Layout

#233 [feat] 유저가 작성한 Board 게시물 조회 API 테스트 코드 작성 및 문서 작성
  server/src/docs/asciidoc/Board-API.adoc
  server/src/main/resources/application.yml
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/MyPet-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
Labels: 🧃Feat

#234 [design] 이미지 속성 추가
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
  client/src/Layout/Header/GNB.tsx
Labels: ✨Layout

#235 [design] MainPeacock 반응형 구현
  client/src/Components/Main/MainPeacock.tsx
Labels: ✨Layout

#236 [feat] question crud
  server/src/main/java/com/Petching/petching/board/dto/BoardDto.java
  server/src/main/java/com/Petching/petching/global/api/jwt/service/ExtractService.java
  server/src/main/java/com/Petching/petching/question/controller/QuestionController.java
  server/src/main/java/com/Petching/petching/question/dto/QuestionDto.java
  server/src/main/java/com/Petching/petching/question/entity/Question.java
  server/src/main/java/com/Petching/petching/question/mapper/QuestionMapper.java
  server/src/main/java/com/Petching/petching/question/repository/QuestionRepository.java
  server/src/main/java/com/Petching/petching/question/service/QuestionService.java
  server/src/main/java/com/Petching/petching/temp/chat/config/RedisConfig.java
  server/src/main/java/com/Petching/petching/temp/chat/config/WebSocketConfig.java
Labels: 🧃Feat

#237 [feat] MainMember 반응형 구현
  client/src/Components/Main/MainMember.tsx
  client/src/Components/Main/Members.tsx
Labels: 🧃Feat, ✨Layout

#238 [feat] question crud
  server/src/main/java/com/Petching/petching/question/controller/QuestionController.java
  server/src/main/java/com/Petching/petching/question/dto/QuestionDto.java
  server/src/main/java/com/Petching/petching/question/entity/Question.java
  server/src/main/java/com/Petching/petching/question/mapper/QuestionMapper.java
  server/src/main/java/com/Petching/petching/question/repository/QuestionRepository.java
  server/src/main/java/com/Petching/petching/question/service/QuestionService.java
Labels: 🧃Feat

#240 [feat]TextEditor Img, Content 기능구현
  client/package-lock.json
  client/package.json
  client/src/API/api.ts
  client/src/Components/Care/TextEditor.tsx
  client/src/Page/InqueryWrite.tsx
  client/src/Page/peacockWrite.tsx
Labels: 🧃Feat

#242 [fe]peacockwrite 게시물 등록
  client/src/Components/Care/PeacockTextEditor.tsx
  client/src/Components/peacockComponent.tsx
  client/src/Hook/usePostPeacock.ts
  client/src/Page/Peacock.tsx
  client/src/Page/peacockWrite.tsx
  client/src/store/PeacockStore.ts
Labels: 🧃Feat

#245 [feat] question api 테스트 코드 작성 및 문서 작성
  server/build.gradle
  server/src/main/java/com/Petching/petching/question/controller/QuestionController.java
  server/src/main/java/com/Petching/petching/question/dto/QuestionDto.java
  server/src/main/java/com/Petching/petching/temp/chat/controller/MessageController.java
  server/src/main/java/com/Petching/petching/temp/chat/controller/RoomController.java
  server/src/main/java/com/Petching/petching/temp/chat/redis/RedisSubscriber.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/QuestionControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/mock/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/comment/CommentControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/jwt/JwtControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/login/LoginTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/mypet/MyPetControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/question/QuestionControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: 🧃Feat

#248 [refactor] question api 문서 수정
  server/src/main/resources/static/docs/CarePost-API.html
  server/src/main/resources/static/docs/Comment-API.html
  server/src/main/resources/static/docs/JWT-API.html
  server/src/main/resources/static/docs/MyPet-API.html
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
Labels: refactor
