Repository Petching/Petching, pull requests merged in 2023-07, with the labels that each got.

#33 [feat]kakao oauth 코드 추가
  .github/workflows/action.yml
  client/.env
  client/package-lock.json
  client/package.json
  client/src/API/signIn.ts
  client/src/API/signUp.ts
  client/src/Components/Kakao.tsx
  client/src/Components/KakaoLogin.tsx
  client/src/Components/signInComponent.tsx
  client/src/Components/signUpComponent.tsx
  client/src/Page/signIn.tsx
  client/src/Util/getCookie.ts
  client/src/Util/types.ts
  client/src/router.tsx
Labels: 🧃Feat

#35 [feat] main페이지 react-query 임시 적용
  client/package-lock.json
  client/package.json
  client/src/Hook/useGetMainData.ts
  client/src/index.tsx
Labels: 🧃Feat

#37 [feat] react-query UserInfo 임의 적용
  client/package-lock.json
  client/package.json
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useGetUserProfile.ts
  client/src/Page/User.tsx
  client/tailwind.config.js
Labels: 🧃Feat

#38 [feat] 마이펫 항목 추가
  client/src/Components/User/AddPet.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Components/User/UserInfo.tsx
Labels: 🧃Feat

#42 [refactor] Edit Auditable.java
  server/src/main/java/com/Petching/petching/audit/Auditable.java
Labels: refactor

#45 [refactor] Edit Auditable.java
  server/src/main/java/com/Petching/petching/carepost/entity/CarePost.java
Labels: refactor

#48 [refactor] Edit User entity, Auditable
  server/src/main/java/com/Petching/petching/user/entity/User.java
Labels: refactor

#46 [refactor] Edit Auditable.java
  .github/workflows/gradle.yml
  server/src/main/java/com/Petching/petching/login/jwt/filter/JwtAuthenticationProcessingFilter.java
  server/src/main/java/com/Petching/petching/user/entity/User.java
Labels: refactor

#65 [feat]peacockdetail 페이지 ui 구성
  client/src/Components/peacockComponent.tsx
  client/src/Page/peacockDetail.tsx
  client/src/Page/peacockWrite.tsx
  client/src/router.tsx
Labels: 🧃Feat

#66 [feat] UserProfile 기능 구현
  client/src/Components/User/UserInfo.tsx
  client/src/Hook/useDeleteUserProfile.ts
  client/src/Hook/useGetUserProfile.ts
  client/src/Hook/usePatchUserProfile.ts
Labels: 🧃Feat

#71 [feat] MyPet 수정 기능 구현
  client/src/Components/User/MyPets.tsx
  client/src/Components/User/PetCard.tsx
  client/src/Hook/usePatchMyPet.ts
Labels: 🧃Feat

#75 [feat] Main 페이지 데이터 연결, router 버튼 연결
  client/src/Components/Main/Explan.tsx
  client/src/Components/Main/Info.tsx
  client/src/Components/Main/MainPeacock.tsx
  client/src/Hook/useGetMainData.ts
Labels: good first issue, 🧃Feat

#76 [feat] Board - Comment 간 CRUD 완성, S3 파일 업로드 여러 개로 할 수 있게 refactoring
  server/src/main/java/com/Petching/petching/aws/s3/client/CustomS3Client.java
  server/src/main/java/com/Petching/petching/aws/s3/service/UploadToS3.java
  server/src/main/java/com/Petching/petching/board/controller/BoardController.java
  server/src/main/java/com/Petching/petching/board/dto/BoardDto.java
  server/src/main/java/com/Petching/petching/board/entity/Board.java
  server/src/main/java/com/Petching/petching/board/repository/BoardRepository.java
  server/src/main/java/com/Petching/petching/board/service/BoardService.java
  server/src/main/java/com/Petching/petching/comment/controller/CommentController.java
  server/src/main/java/com/Petching/petching/comment/dto/CommentDto.java
  server/src/main/java/com/Petching/petching/comment/entity/Comment.java
  server/src/main/java/com/Petching/petching/comment/service/CommentService.java
  server/src/main/java/com/Petching/petching/global/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/Petching/petching/global/api/ec2/controller/HealthCheckController.java
  server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
  server/src/main/java/com/Petching/petching/global/aws/s3/config/S3Configuration.java
  server/src/main/java/com/Petching/petching/global/aws/s3/dto/S3FileDto.java
  server/src/main/java/com/Petching/petching/global/aws/s3/service/S3Service.java
  server/src/main/resources/application.yml
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
Labels: 🧃Feat

#78 [feat] Rest Docs API 문서화 - S3 controller
  server/build.gradle
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
  server/src/main/java/com/Petching/petching/user/dto/UserPatchDto.java
  server/src/main/java/com/Petching/petching/user/dto/UserPostDto.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/temp/1.png
  server/src/main/resources/static/temp/2.png
  server/src/main/resources/static/temp/3.jpg
  server/src/test/java/com/Petching/petching/restDocs/global/helper/S3ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
Labels: 🧃Feat

#79 [feat] Rest Docs API 문서화 - BoardController
  server/src/main/java/com/Petching/petching/board/controller/BoardController.java
  server/src/main/java/com/Petching/petching/board/dto/BoardDto.java
  server/src/main/java/com/Petching/petching/board/entity/Board.java
  server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: 🧃Feat

#80 [refactor] S3Service, index.adoc 수정
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/Petching/petching/global/aws/s3/service/S3Service.java
Labels: refactor

#92 [refactor] BoardControllerTest security config
  server/build.gradle
  server/src/main/java/com/Petching/petching/board/controller/BoardController.java
  server/src/main/java/com/Petching/petching/global/api/s3/controller/S3Controller.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/S3ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: refactor

#93 [feat] API DOCS - BoardController, UserController, S3Controller
  server/build.gradle
  server/src/docs/asciidoc/S3-API.adoc
  server/src/docs/asciidoc/User-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/docs/asciidoc/자랑하기-API.adoc
  server/src/main/java/com/Petching/petching/board/controller/BoardController.java
  server/src/main/resources/static/docs/custom-ui.html
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/S3ControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/StubData.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/carepost/CarePostControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  server/src/test/resources/org/springframework/restdocs/templates/request-parameters.snippet
Labels: 🧃Feat

#95 [refactor] remote 환경에서 build 안되는 이슈로 인한 시스템 속성 설정
  server/src/main/resources/application.yml
Labels: refactor

#97 [refactor] remote 환경에서 build 안되는 이슈로 인한 테스트 코드 수정
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/s3/S3ControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: refactor

#100 [refactor] API Docs request - host 수정
  server/src/main/java/com/Petching/petching/global/aws/s3/service/S3Service.java
  server/src/main/resources/static/docs/S3-API.html
  server/src/main/resources/static/docs/User-API.html
  server/src/main/resources/static/docs/index.html
  server/src/main/resources/static/docs/자랑하기-API.html
  server/src/test/java/com/Petching/petching/restDocs/global/helper/BoardControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/helper/UserControllerTestHelper.java
  server/src/test/java/com/Petching/petching/restDocs/global/utils/ApiDocumentUtils.java
  server/src/test/java/com/Petching/petching/restDocs/v1/board/BoardControllerTest.java
  server/src/test/java/com/Petching/petching/restDocs/v1/user/UserControllerTest.java
Labels: refactor

#103 [refactor] MainData 변경된 형식 적용
  client/src/Components/Main/MainPeacock.tsx
  client/src/Hook/useGetMainData.ts
Labels: refactor

#107 [feat] Board조회 데이터 불러오기
  client/src/Components/Care/Board.tsx
  client/src/Components/Care/Carousel.tsx
  client/src/Components/Care/TextEditor.tsx
  client/src/Page/CareList.tsx
Labels: 🧃Feat
